export const HANDLE_FILTER_ABSTENCAO = "HANDLE_FILTER_ABSTENCAO";
export const HANDLE_DATA_ABSTENCAO = "HANDLE_DATA_ABSTENCAO";

export const HANDLE_FILTER_ELEITORADO = "HANDLE_FILTER_ELEITORADO";
export const HANDLE_FILTER_RENDA = "HANDLE_FILTER_RENDA";

export const GET_CIDADES = "GET_CIDADES";


