const data = [
  {
    NM_MUNICIPIO: "CARAPICUÍBA",
    QT_ELEITORES_PERFIL: 291604,
    QT_ELEITORES_INC_NM_SOCIAL: 34,
    QT_ELEITORES_DEFICIENCIA: 3262,
  },
  {
    NM_MUNICIPIO: "BARUERI",
    QT_ELEITORES_PERFIL: 261786,
    QT_ELEITORES_INC_NM_SOCIAL: 15,
    QT_ELEITORES_DEFICIENCIA: 26140,
  },
  {
    NM_MUNICIPIO: "SÃO JOSÉ DOS CAMPOS",
    QT_ELEITORES_PERFIL: 475288,
    QT_ELEITORES_INC_NM_SOCIAL: 50,
    QT_ELEITORES_DEFICIENCIA: 4971,
  },
];

module.exports = data;
